### ISSUE TITLE
Basic Frontend Navbar Using React

### ISSUE THREAD

**Issue by KaranSinghBisht** [KaranSinghBisht/Space-Frontend#1]
For the website, We need a simple Navbar made using React 
For css you can use any framework or library you want to use.

**Comment by roygrv21** [comment]
Can I take this issue?

**Comment by CodeSmitty** [comment]
interested

**Comment by CodeSmitty** [comment]
ty :)

**Comment by dalegacusan** [comment]
Can I still take this issue?

**Comment by KaranSinghBisht** [comment]
Assigned

**Comment by iampankajgupta** [comment]
can i work on this issue

**Comment by KaranSinghBisht** [comment]
It's assigned @iampankajgupta

**Comment by iampankajgupta** [comment]
okk no problem

**Comment by ArpitaGanatra** [comment]
Can I work on this issue?

**Comment by st-currenxie** [comment]
Do you want to include adding react-router in this issue @KaranSinghBisht ? Are there any links you have in mind for the navbar?

**Comment by inovux** [comment]
Shall we include react-router to this issue as well? What nav links are you thinking of having for this project? @KaranSinghBisht

**Comment by KaranSinghBisht** [comment]
> Shall we include react-router to this issue as well? What nav links are you thinking of having for this project? @KaranSinghBisht 

Yes use React routers
The nav bar links would be Home, Explore, Forums and then sign-up or login as per the state of the user

**Comment by inovux** [comment]
@KaranSinghBisht This is done by the way :)

**Comment by KaranSinghBisht** [comment]
@inovux I'll close the issue after checking it tomorrow 
Thanks for a heads up tho :smile:
