### ISSUE TITLE
Logo Needed

### ISSUE THREAD

**Issue by KaranSinghBisht** [KaranSinghBisht/Space-Frontend#2]
Logo to be used in the navbar and other places needed
Text to be a light color as the whole website would be in a kind of dark mode

**Comment by adripo** [comment]
How about this one?
![immagine](https://user-images.githubusercontent.com/26493496/95000809-59028b80-05c4-11eb-805a-dfb790c21f61.png)

**Comment by adripo** [comment]
Or this one for dark mode

![immagine](https://user-images.githubusercontent.com/26493496/95000858-d1694c80-05c4-11eb-90f5-bc6b5dd4cb31.png)

**Comment by lucid-dreem** [comment]
Hey, could you give some guidelines regarding what you would like the logo to look like, since otherwise there's nothing to work off of

**Comment by KaranSinghBisht** [comment]
https://raw.githubusercontent.com/hot9cups/website-for-friend/master/possible_logos/LogoPng.png
See Like this is one of the logos I made for another repo @lucid-dreem, Something of this sort

**Comment by KaranSinghBisht** [comment]
The logo should be of neon/green colour and the text should be white as the website is dark themed

**Comment by lucid-dreem** [comment]
I commented an updated logo in neon green and white text in the same pull request. Let me know if that works.
