### ISSUE TITLE
Forum Section Card Component

### ISSUE THREAD

**Issue by KaranSinghBisht** [KaranSinghBisht/Space-Frontend#21]
This is a really Easy issue to be honest
Just make a resusable card component using react which is small in height and takes around 60% width wise 
(Like small rectangles with big length and small width, if this makes sense)

These components will contain a title for the post a user will make and the user name below the title

Use font awesome or materialUI for a edit icon(✏️ like this one) on the right side of the card component. (The backend part like if the user is logged in then show the icon will be handled in the backend so don't worry about that)

Also everyone is encouraged to submit the card components

**Comment by Jp1200** [comment]
Im interested, mind assigning?

**Comment by iampankajgupta** [comment]
Can I work on this issue

**Comment by Borumer** [comment]
I'm up to work on this issue

**Comment by rohanshenoy96** [comment]
I would like to work on this. Can you please assign me this
