### ISSUE TITLE
Sign up and Sign in

### ISSUE THREAD

**Issue by sakshi-s** [KaranSinghBisht/Space-Frontend#29]
Add a Sign up button to the right of Sign in and add a form for the same.

**Comment by sakshi-s** [comment]
@KaranSinghBisht I would like to have your views on this.

**Comment by KaranSinghBisht** [comment]
Great 👌
One can use react routers and add the sign-up form page

**Comment by sakshi-s** [comment]
Okay then I can start working on this. You can assign it to me. @KaranSinghBisht

**Comment by rohanshenoy96** [comment]
I can see a sign in link. Can I create a PR with some nice stylings? Or is this what you wanted @KaranSinghBisht?
