### ISSUE TITLE
Improving Documentation / README.md

### ISSUE THREAD

**Issue by KaranSinghBisht** [KaranSinghBisht/Space-Frontend#3]
There is almost know information about how the site looks like or even about anything and that is because
I want this to be a open source project with multiple users contributing and having discussions on the way...

I would like to have discussions and listen to your ideas and opinions on how you would want a site to look like
(Remember this is a forums bases website)

**Comment by vieee** [comment]
Hi @KaranSinghBisht, could I take this up..

**Comment by thisis-Solomon** [comment]
what was the first visual idea of the website look when you were coming with the site's name and its category????
why have asked this question is to have an idea on its should flowing and tools to use.

**Comment by tanujajoshi1** [comment]
Hey Can I work on it

**Comment by KaranSinghBisht** [comment]
Yes

**Comment by Justobioma** [comment]
I would like to be a part of this.
