### ISSUE TITLE
Footer Component Needed (React)

### ISSUE THREAD

**Issue by KaranSinghBisht** [KaranSinghBisht/Space-Frontend#4]
A Footer component is needed for the website with a newsletter component and links to other social media ( Github repo, Facebook etc using Icons )

Feel free to use anything you are comfortable with React like Bootstrap, Tailwindcss, Sass, Material-UI for icons etc

**Comment by EugeneKoleda** [comment]
Hello!
Can I take this?

**Comment by kaushiksriram16** [comment]
Can I work on this?

**Comment by Nimanita** [comment]
@KaranSinghBisht  Will you please assign it to me?

**Comment by KaranSinghBisht** [comment]
Guys start working on it
@EugeneKoleda @kaushiksriram16 @Nimanita 
If you guys are from hacktoberfest, 
And even if your pr doesn't get merged but is of good quality I'll add a hacktoberfest Accepted label so that it counts towards the shirt

**Comment by kaushiksriram16** [comment]
@KaranSinghBisht  If footer component added by any of us is good enough will u merge it?

**Comment by thelavenderhue** [comment]
Can I work on this?

**Comment by KaranSinghBisht** [comment]
Yes @mrinal-27

**Comment by iampankajgupta** [comment]
can i work this issue

**Comment by KaranSinghBisht** [comment]
Yes @iampankajgupta

**Comment by inovux** [comment]
Is there any layout / colors that you think work well for your project? It would help out the people trying to contribute a lot so they have an idea on how things should vaguely look like.

**Comment by KaranSinghBisht** [comment]
@inovux Neon Green is the main color and dark mode kind website
